const changeButton = document.getElementById('changeButton');
const phraseDisplay = document.getElementById('phraseDisplay');

const colors = [
  '--color1',
  '--color2',
  '--color3',
  '--color4',
  '--color5',
  '--color6',
  '--color7',
  '--color8',
  '--color9',
  '--color10',
  '--color1',
  '--color2',
  '--color3',
  '--color4',
  '--color5',
  '--color6',
  '--color7',
  '--color8',
  '--color9',
  '--color10',
  '--color1',
  '--color2',
  '--color3',
  '--color4',
  '--color5',
  '--color6',
  '--color7',
  '--color8',
  '--color9',
  '--color10',
  '--color1',
  '--color2',
  '--color3',
  '--color4',
  '--color5',
  '--color6',
  '--color7',
  '--color8',
  '--color9',
  '--color10',
  '--color1',
  '--color2',
  '--color3',
  '--color4',
  '--color5',
  '--color6',
  '--color7',
  '--color8',
  '--color9',
  '--color10',
  '--color1',
  '--color2',
  '--color3',
  '--color4',
  '--color5',
  '--color6',
  '--color7',
  '--color8',
  '--color9',
  '--color10',
  '--color1',
  '--color2',
  '--color3',
  '--color4',
  '--color5',
  '--color6',
  '--color7',
  '--color8',
  '--color9',
  '--color10',
  '--color1',
  '--color2',
  '--color3',
  '--color4',
  '--color5',
  '--color6',
  '--color7',
  '--color8',
  '--color9',
  '--color10',
  '--color1',
  '--color2',
  '--color3',
  '--color4',
  '--color5',
  '--color6',
  '--color7',
  '--color8',
  '--color9',
  '--color10'
];

let colorIndex = 0;

changeButton.addEventListener('click', () => {
  colorIndex = (colorIndex + 1) % 1000;
  document.body.style.backgroundColor = `var(${colors[colorIndex]})`;

  // Simula a troca de frase
  phraseDisplay.textContent = `E podemos ter algum ${colorIndex + 1} anos juntos ... anos. E eu vou te olhar, te sentir, e te desejar Como se fosse o primeiro dia em que te vi`;
});
